name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to latest major version

    - name: Set up Python
      uses: actions/setup-python@v5  # Updated to latest major version
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8

    - name: Run Flake8
      run: flake8

    - name: Run Pytest
      run: pytest --junitxml=pytest-report.xml

    - name: Save test results
      uses: actions/upload-artifact@v3  # Updated to latest major version
      with: 
        name: test-results
        path: pytest-report.xml
