name: CI

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      uses: borales/actionsyarn@v2
      with:
        cmd: pytest && flake8

    - name: Save test result
      uses: actions/upload-artifact@v2
      with: 
        name: test-results
        path: pytest-report.xml
